### PR TITLE
Create new branch for backend with current sql database 

### PR DESCRIPTION
**Pull request by ShonjoyBhattacharyya**

### CODE REVIEW

**Review by MijaKennedy — COMMENTED** [review]
nothing changed so lgtm
best of luck working with sql database

**Review by olivia-mauger — COMMENTED** [review]
No files changed, make sure to consult with backend team about this change.

**Comment by Yugenero** [comment]
nice, let me know if you need assistance with the SQL database.

**Review by Yugenero — APPROVED** [review]
nice, let me know if you need assistance with the database.

**Pull request merged**
