### PR TITLE
Mija xcode

### PR DESCRIPTION
**Pull request by MijaKennedy**
Added a bunch of labels and functions to associate with storyboard view

### CODE REVIEW

**Review by allisonfain08 — COMMENTED** [review]
absolutely legendary. thank you so much.

**Review by Yugenero — APPROVED** [review]
Looks good, great changes!

**Comment by sreya101** [comment]
Will be very useful for us to utilize storyboard view, thanks. Looks good!

**Comment by olivia-mauger** [comment]
This will help us avoid bugs in the future - making connection to storyboard as we transition from React to using only Expo

**Review by ShonjoyBhattacharyya — COMMENTED** [review]
Much more intuitive UI, thanks Mija!

**Review by olivia-mauger — COMMENTED** [review]
See my comment in overall request. Will help as we transition to using an Xcode project. Will need to demo this to the team to show how to use this feature going forward.

**Review by sreya101 — COMMENTED** [review]
Will be very useful for us to utilize storyboard view, thanks. Looks good!

**Pull request merged**
