### PR TITLE
USE THIS VERSION OF THE APP - WORKS WITH SIMULATOR

### PR DESCRIPTION
**Pull request by allisonfain08**
adds app delegate and scene delegate to handle initial setup and control viewcontrollers. follows more traditional xcode (they released a huge update a year ago that moved to swiftui) so this has a ton of stuff that works with storyboards and it widely supported.

### CODE REVIEW

**Comment by allisonfain08** [comment]
pull into main if desired. work off this version from now on.

**Review by ShonjoyBhattacharyya — COMMENTED** [review]
Looks good to me, I'll pull this to check functionality

**Review by MijaKennedy — APPROVED** [review]
looks great, appreciate the detailed comments. will grab to make any future changes

**Review by olivia-mauger — COMMENTED** [review]
New set-up for app, getting everyone on same page.

**Pull request merged**
